@echo off
echo DD_BUILD_VERSION = %APPVEYOR_BUILD_NUMBER%>"%APPVEYOR_BUILD_FOLDER%\.qmake.conf"
echo DD_COMMIT_ID = %APPVEYOR_REPO_COMMIT%>>"%APPVEYOR_BUILD_FOLDER%\.qmake.conf"
echo DD_COMMIT_TIME  = %APPVEYOR_REPO_COMMIT_TIMESTAMP%>>"%APPVEYOR_BUILD_FOLDER%\.qmake.conf"
