@echo off
echo DD_PATCH_VERSION=%APPVEYOR_BUILD_NUMBER%>"%APPVEYOR_BUILD_FOLDER%\version_ci.pri"
echo DD_COMMIT_ID=%APPVEYOR_REPO_COMMIT%>>"%APPVEYOR_BUILD_FOLDER%\version_ci.pri"
echo DD_COMMIT_TIME=%APPVEYOR_REPO_COMMIT_TIMESTAMP%>>"%APPVEYOR_BUILD_FOLDER%\version_ci.pri"
echo DEFINES *= DD_NIGHTLY_BUILD>>"%APPVEYOR_BUILD_FOLDER%\version_ci.pri"
echo DEFINES *= DD_COMMIT_ID=\\\"$${DD_COMMIT_ID}\\\">>"%APPVEYOR_BUILD_FOLDER%\version_ci.pri"
echo DEFINES *= DD_COMMIT_TIME=\\\"$${DD_COMMIT_TIME}\\\">>"%APPVEYOR_BUILD_FOLDER%\version_ci.pri"
